[package]
name = "fd2023_01_text_adventure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_ascii_terminal = "0.12.1"
ascii_utils = "0.9.3"
